FROM ubuntu:24.04

# ------------------------------------------------------------
# general metadata about the container

# hard coded args
LABEL author="J Rabault"
LABEL ContainerfileLocation="https://github.com/jerabaul29/containerized_development_environment/tree/main/development_with_platformio"
LABEL kind="guiserving_application"
LABEL version="0.1"
LABEL description="A container packing a full platformio-based development environment."

# automatically grabbed hash
# require to build with flag `--build-arg GIT_HASH="$(git rev-parse HEAD)"`
ARG GIT_HASH="0"
LABEL GIT_HASH=$GIT_HASH
ENV GIT_HASH=$GIT_HASH

# automatically grabbed posix creation time
# require to build with flag `-build-arg POSIX_TIMESTAMP_CREATION="$(date +%s)"`
ARG POSIX_TIMESTAMP_CREATION="0"
LABEL POSIX_TIMESTAMP_CREATION=$POSIX_TIMESTAMP_CREATION
ENV POSIX_TIMESTAMP_CREATION=$POSIX_TIMESTAMP_CREATION

# ------------------------------------------------------------
# all root operations (apt install etc)

USER root

# make sure to use full true colors
ENV TERM xterm-256color
ENV COLORTERM truecolor

# all sudo apt operations in one go; update cache, install, purge cache
RUN apt-get update && apt-get install -y \
    # needed for GUI applications
    xauth \
    xorg \
    # needed by vsc
    dbus \
    # needed to add MS key
    gpg \
    # my usual utils...
    wget \
    git \
    tmux \
    htop \
    tree \
    # stuff for platformio
    python3.12-venv \
    && rm -rf /var/lib/apt/lists/*

# install VSC

WORKDIR /home/root/Software/VSC

RUN echo "code code/add-microsoft-repo boolean true" | debconf-set-selections

RUN wget "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64" -O code.deb && \
    apt update && apt install -y ./code.deb

RUN useradd platformio_ubuntu
# TODO: set shell?

# ------------------------------------------------------------
# all user level operations

USER platformio_ubuntu

# TODO: install platformio?
# platformio_ubuntu@contdev:~$ wget -O get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
# platformio_ubuntu@contdev:~$ python3 get-platformio.py
# and make avail: this or similar:
# ln -s ~/.platformio/penv/bin/platformio ~/.local/bin/platformio
# ln -s ~/.platformio/penv/bin/pio ~/.local/bin/pio


# make sure to use full true colors
ENV TERM xterm-256color
ENV COLORTERM truecolor

WORKDIR /home/platformio_ubuntu

# ----------------------------------------
# default command is to get a shell

# TODO: load bashrc etc

CMD /bin/bash -c 'if (( "$(date +%s)" > $((POSIX_TIMESTAMP_CREATION+604800)) )); then read -p "WARNING; the container is built for more than 7 days ago; consider re-building! press ENTER to continue"; fi' && \
    /bin/bash
