FROM ubuntu:24.04

# ------------------------------------------------------------
# general metadata about the container

# hard coded args
LABEL author="J Rabault"
LABEL ContainerfileLocation="https://github.com/jerabaul29/containerized_development_environment/tree/main/development_with_helix"
LABEL kind="commandline_application"
LABEL version="0.1"
LABEL description="A container packing a full helix-based development environment."

# automatically grabbed hash
# require to build with flag `--build-arg GIT_HASH="$(git rev-parse HEAD)"`
ARG GIT_HASH="0"
LABEL GIT_HASH=$GIT_HASH
ENV GIT_HASH=$GIT_HASH

# automatically grabbed posix creation time
# require to build with flag `-build-arg POSIX_TIMESTAMP_CREATION="$(date +%s)"`
ARG POSIX_TIMESTAMP_CREATION="0"
LABEL POSIX_TIMESTAMP_CREATION=$POSIX_TIMESTAMP_CREATION
ENV POSIX_TIMESTAMP_CREATION=$POSIX_TIMESTAMP_CREATION

# ------------------------------------------------------------
# all root operations (apt install etc)

USER root

# make sure to use full true colors
ENV TERM xterm-256color
ENV COLORTERM truecolor

# all sudo apt operations in one go; update cache, install, purge cache
RUN apt-get update && apt-get install -y \
    # needed to run appimage apps
    libfuse2t64 \
    wget \
    git \
    tmux \
    htop \
    tree \
    && rm -rf /var/lib/apt/lists/*

# prepare default user and set default shell
# TODO: is that enough for tmux to invoke /bin/bash? does tmux need any more magics or similar?
RUN useradd helix_ubuntu
RUN usermod -s /bin/bash helix_ubuntu

# TODO: make sure all new terminals source the .bashrc for helix_ubuntu

# ------------------------------------------------------------
# all user level operations

USER helix_ubuntu

# make sure to use full true colors
ENV TERM xterm-256color
ENV COLORTERM truecolor

# ----------------------------------------
# installation of conda

WORKDIR /home/helix_ubuntu/Software/conda

RUN wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" && \
    bash Miniforge3-$(uname)-$(uname -m).sh -b -p /home/helix_ubuntu/Software/conda/miniconda

# ----------------------------------------
# installation of helix

WORKDIR /home/helix_ubuntu/Software/helix

RUN wget --https-only https://github.com/helix-editor/helix/releases/download/24.07/helix-24.07-x86_64.AppImage && \
    chmod +x helix-24.07-x86_64.AppImage && \
    # for some reason, appimages cannot be just run within podman containers - need to extract and then run the executable
    ./helix-24.07-x86_64.AppImage --appimage-extract

# ----------------------------------------
# cloning of relevant configurations and add ons

WORKDIR /home/helix_ubuntu

RUN \
    # my configs
    git clone https://github.com/jerabaul29/config_scripts_snippets.git --depth=1 && \
    # set up helix config
    mkdir -p /home/helix_ubuntu/.config/helix/ && cp /home/helix_ubuntu/config_scripts_snippets/configs/helix/config.toml /home/helix_ubuntu/.config/helix/config.toml && \
    # install fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && \
    ~/.fzf/install && \
    # nice tmux conf
    git clone https://github.com/gpakosz/.tmux.git /home/helix_ubuntu/.tmux --depth=1 && \
    ln -s -f .tmux/.tmux.conf && \
    cp config_scripts_snippets/configs/tmux/.tmux.conf.local . && \
    # nice prompt also in git repos
    git clone https://github.com/magicmonty/bash-git-prompt.git /home/helix_ubuntu/.bash-git-prompt --depth=1 && \
    echo "if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then\nGIT_PROMPT_ONLY_IN_REPO=0\nGIT_PROMPT_THEME=Single_line_Dark\nsource $HOME/.bash-git-prompt/gitprompt.sh\nfi" >> .bashrc

# ----------------------------------------
# setup of bashrc

# TODO: install zg, zx, hg, hx, ga, etc
# TODO: add alias p for python3

WORKDIR /home/helix_ubuntu
RUN echo 'alias hlx="/home/helix_ubuntu/Software/helix/squashfs-root/AppRun"' >> .bashrc && \
    echo 'alias hj="/home/helix_ubuntu/config_scripts_snippets/scripts/helix_and_repl/helix_and_repl.sh"' >> .bashrc && \
    echo 'source /home/helix_ubuntu/Software/conda/miniconda/etc/profile.d/conda.sh' >> .bashrc && \
    echo 'conda activate base' >> .bashrc

# ----------------------------------------
# prepare project folder, ready to mount

WORKDIR /home/helix_ubuntu/host_mountpoint
# this has to be mounted by the container user, using the argument
# `--volume PATH_ON_HOST:/home/helix_ubuntu/host_mountpoint `

# ----------------------------------------
# TODO: share the conda env packages across runs by mounting "conda env content" part?
# this may not require anything on the side of the container?
# TODO: share the history across container restarts? simply mount the folder / files with the corresponding files?

# ----------------------------------------
# default command is to get a shell with bashrc loaded
# at the host mountpoint location, so this can start to
# be edited

# TODO: have this as an own script, and just call the script; this way can be arbitrarily complex without issue
CMD /bin/bash -c 'if (( "$(date +%s)" > $((POSIX_TIMESTAMP_CREATION+604800)) )); then read -p "WARNING; the container is built for more than 7 days ago; consider re-building! press ENTER to continue"; fi' && \
    /bin/bash --init-file /home/helix_ubuntu/.bashrc

# TODO: run the correct instance of hj if relevant
# TODO: if relevant volume arg provided, activate the provided conda env from the user domain while mounting the folder
# TODO: check that can use matplotlib figures etc
# TODO: default code inside container in conda to allow static code analysis and exploration of projects in python and rust and cpp; but make it easy to mount an external conda if necessary

