FROM ubuntu:24.04

# ------------------------------------------------------------
# general metadata about the container

# hard coded args
LABEL author="J Rabault"
LABEL ContainerfileLocation="https://github.com/jerabaul29/containerized_development_environment/tree/main/development_with_helix"
LABEL kind="commandline_application"
LABEL version="0.1"
LABEL description="A container packing a full helix-based development environment."

# automatically grabbed hash
# require to build with flag `--build-arg GIT_HASH="$(git rev-parse HEAD)"`
ARG GIT_HASH="0"
LABEL GIT_HASH=$GIT_HASH
ENV GIT_HASH=$GIT_HASH

# automatically grabbed posix creation time
# require to build with flag `-build-arg POSIX_TIMESTAMP_CREATION="$(date +%s)"`
ARG POSIX_TIMESTAMP_CREATION="0"
LABEL POSIX_TIMESTAMP_CREATION=$POSIX_TIMESTAMP_CREATION
ENV POSIX_TIMESTAMP_CREATION=$POSIX_TIMESTAMP_CREATION

# ------------------------------------------------------------
# all root operations (apt install etc)

USER root

# ----------------------------------------

# make sure to use full true colors
ENV TERM xterm-256color
ENV COLORTERM truecolor

# ----------------------------------------

# TODO: github cli

# all sudo apt operations in one go; update cache, install, purge cache
RUN apt-get update && apt-get install -y \
    # needed to run appimage apps
    libfuse2t64 \
    wget \
    git \
    tmux \
    htop \
    tree \
    # support user applications, helix etc and necessary tooling to install lsps
    # in particular, we support LSPs for bash, python, cpp, rust
    # this requires quite a bit of tooling...
    golang \
    nodejs \
    npm \
    shellcheck \
    curl \
    # NOTE: this only installs tooling, not rust itself; need
    # 'RUN rustup default stable'
    # in addition for each user who wants to use cargo / rustc etc
    rustup \
    && rm -rf /var/lib/apt/lists/*

# ----------------------------------------
# LSPs for supporting languages that must be installed by root

# TODO: check what should be installed here vs for the user

# support bash lsp in helix
RUN go install mvdan.cc/sh/v3/cmd/shfmt@latest
RUN npm i -g bash-language-server

# TODO: support rust lsp in helix

# TODO: support python lsp in helix

# TODO: support cpp lsp in helix

# ----------------------------------------
# LSPs with general properties that must be installed by root

# ------------------------------------------------------------
# prepare default user and set default shell
RUN useradd helix_ubuntu
RUN usermod -s /bin/bash helix_ubuntu

# ------------------------------------------------------------
# all user level operations

USER helix_ubuntu

# make sure to use full true colors
ENV TERM xterm-256color
ENV COLORTERM truecolor

WORKDIR /home/helix_ubuntu

# make sure to set the user .profile, so that e.g. /bin/bash loads .bashrc, user binaries are loaded, etc
# NOTE: copy always copies as root by default, even though the USER is set otherwise...
COPY --chown=helix_ubuntu:helix_ubuntu profile_content /home/helix_ubuntu/.profile

# copy the bashrc
# NOTE: copy always copies as root by default, even though the USER is set otherwise...
COPY --chown=helix_ubuntu:helix_ubuntu  bashrc /home/helix_ubuntu/.bashrc

# ----------------------------------------
# installation of conda

WORKDIR /home/helix_ubuntu/Software/conda

RUN wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" && \
    bash Miniforge3-$(uname)-$(uname -m).sh -b -p /home/helix_ubuntu/Software/conda/miniconda

# ----------------------------------------
# installation of helix

WORKDIR /home/helix_ubuntu/Software/helix

RUN wget --https-only https://github.com/helix-editor/helix/releases/download/25.01/helix-25.01-x86_64.AppImage && \
    chmod +x helix-25.01-x86_64.AppImage && \
    # for some reason, appimages cannot be just run within podman containers - need to extract and then run the executable
    ./helix-25.01-x86_64.AppImage --appimage-extract

# ----------------------------------------
# installation of rust and rust-based lsps etc

WORKDIR /home/helix_ubuntu

RUN rustup default stable && \
    cargo install --git https://github.com/estin/simple-completion-language-server.git && \
    # harper natural text LSP
    cargo install harper-ls --locked

# NOTE: this does not work...
# ENV PATH "$HOME/.cargo/bin:$PATH"
# TODO: check harper works now

# TODO: typos-lsp
# TODO: install snippets

# ----------------------------------------
# cloning of relevant configurations and add ons

WORKDIR /home/helix_ubuntu

RUN \
    # my configs
    git clone https://github.com/jerabaul29/config_scripts_snippets.git --depth=1 && \
    # set up helix config
    mkdir -p /home/helix_ubuntu/.config/helix/ && cp /home/helix_ubuntu/config_scripts_snippets/configs/helix/config.toml /home/helix_ubuntu/.config/helix/config.toml && \
    # install fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && \
    ~/.fzf/install && \
    # nice tmux conf
    git clone https://github.com/gpakosz/.tmux.git /home/helix_ubuntu/.tmux --depth=1 && \
    ln -s -f .tmux/.tmux.conf && \
    cp config_scripts_snippets/configs/tmux/.tmux.conf.local . && \
    # nice prompt also in git repos
    git clone https://github.com/magicmonty/bash-git-prompt.git /home/helix_ubuntu/.bash-git-prompt --depth=1

# TODO: install zg, zx, hg, hx, ga, etc
# TODO: add alias p for python3

# TODO: custom hj version?
# TODO: only enable conda if relevant; load the default conda environment
# TODO: both based on env variables or command line arguments?
# hj ENV FILE
# ENV:
# - name
# - path
# - NONE
# - no arg

# ----------------------------------------
# prepare the external conda env folder, ready to mount

# this volume has to be mounted by the container user, using the argument
# `--volume PATH_ON_HOST:/home/helix_ubuntu/host_mountpoint_conda_env`
WORKDIR /home/helix_ubuntu/host_mountpoint_conda_env

# ----------------------------------------
# prepare project folder, ready to mount

# this has to be mounted by the container user, using the argument
# `--volume PATH_ON_HOST:/home/helix_ubuntu/host_mountpoint_project`
WORKDIR /home/helix_ubuntu/host_mountpoint_project

# ----------------------------------------
# TODO: share the conda env packages across runs by mounting "conda env content" part?
# this may not require anything on the side of the container?
# TODO: share the history across container restarts? simply mount the folder / files with the corresponding files?

# ----------------------------------------
# default command is to get a shell with bashrc loaded
# at the host mountpoint location, so this can start to
# be edited

# TODO: have this as an own script, and just call the script; this way can be arbitrarily complex without issue
CMD /bin/bash -c 'if (( "$(date +%s)" > $((POSIX_TIMESTAMP_CREATION+604800)) )); then read -p "WARNING; the container is built for more than 7 days ago; consider re-building! press ENTER to continue"; fi' && \
    /bin/bash --init-file /home/helix_ubuntu/.bashrc

# TODO: run the correct instance of hj if relevant
# TODO: if relevant volume arg provided, activate the provided conda env from the user domain while mounting the folder
# TODO: check that can use matplotlib figures etc
# TODO: default code inside container in conda to allow static code analysis and exploration of projects in python and rust and cpp; but make it easy to mount an external conda if necessary

